### ISSUE TITLE
Create a page for Privacy Policy

### ISSUE THREAD

**Issue by Timtech4u** [DSCBUK/dscbuk.github.io#7]
We need some Privacy Policy contents, try to generate some and put them on a new page.

**Comment by Sergioamjr** [comment]
Hi, @Timtech4u. I can help you. I'll create a Privacy Policy page with a Lorem Ipsum content for you edit them after, ok?

**Comment by Sergioamjr** [comment]
https://github.com/DSCBUK/dscbuk.club/pull/12
