### ISSUE TITLE
Link Help Center to our Twitter Page

### ISSUE THREAD

**Issue by Timtech4u** [DSCBUK/dscbuk.github.io#8]
Create a hyperlink for Help Center that directs users to our twitter handle `@dscbuk`

**Comment by maliMirkec** [comment]
I'm on it!

**Comment by maliMirkec** [comment]
@Timtech4u Are you referring to Help Center in the footer only?

**Comment by Timtech4u** [comment]
Yes @maliMirkec . 

But sorry this is meant for DSCBUK members alone.

**Comment by maliMirkec** [comment]
No problem. Did you attach [hacktoberfest](https://github.com/DSCBUK/dscbuk.club/labels/hacktoberfest) label accidentally?
